FROM python:3.7-alpine

RUN pip install pipenv

ENV PYTHONUNBUFFERED=1\
    DJANGO_SETTINGS_MODULE=config.settings.dev

WORKDIR /usr/src/app/

COPY Pipfile /usr/src/app/
COPY Pipfile.lock /usr/src/app/

RUN pipenv install --system
COPY . /usr/src/app/

RUN python manage.py collectstatic --no-input

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]

