version: '3'

services:
  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile_dev

  nginx:
    restart: always
    build:
      context: ./nginx/
      dockerfile: Dockerfile_dev
    ports:
      - "80:80"
    depends_on:
      - web
