version: '3'

networks:
  frontend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.10.1.0/24
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.10.2.0/23

services:
  mysql:
    restart: always
    build: ./mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    networks:
      backend:
        ipv4_address: 172.10.3.2

  web:
    restart: always
    build: ./web
    volumes:
      - ./src:/var/www/html/
    ports:
      - "80:80"
    depends_on:
      - mysql
    networks:
      backend:
        ipv4_address: 172.10.2.2
      frontend:
        ipv4_address: 172.10.1.2