version: '3'

services:
  mysql:
    restart: always
    build: ./mysql
    command: --default-authentication-plugin=mysql_native_password
    expose:
      - 3306

  web:
    restart: always
    build: ./web
    volumes:
      - ./src:/var/www/html/
    ports:
      - "80:80"
    depends_on:
      - mysql
