FROM python:3.7-alpine

RUN pip install pipenv

ENV PYTHONUNBUFFERED=1\
    DJANGO_SETTINGS_MODULE=config.settings._dev

RUN mkdir -p /usr/src/app/mb_project
WORKDIR /usr/src/app/mb_project

COPY Pipfile /usr/src/app/mb_project
COPY Pipfile.lock /usr/src/app/mb_project

RUN pipenv install --system
COPY . /usr/src/app/mb_project

RUN python manage.py collectstatic --no-input
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
