version: '3'

services:
  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile_dev
    volumes:
      - .:/usr/src/app/mb_project/
    expose:
      - 8000

  nginx:
    restart: always
    build:
      context: ./nginx/
      dockerfile: Dockerfile_dev
    volumes:
      - ./website/static:/usr/src/app/mb_project/static/
    ports:
      - "80:80"
    depends_on:
      - web
